### ISSUE TITLE
Labs not working..

### ISSUE THREAD

**Issue by ibmkaga** [aws-samples/protecting-workloads-workshop#10]
CF template gives error of PermissionDenied for S3 location that it references.
If i download the template from the github /template location and try to specify that on my local drive, then it fails at the ASG healthcheck and Rollbacks the entire stack.
Can someone look at this and see what i might be missing?

Thanks and Regards.

**Comment by jeffsec-aws** [comment]
Unfortunately it does not deploy as the other artifact [https://s3.amazonaws.com/protecting-workloads-workshop/public/artifacts/pww_site.zip] also returns a 403

**Comment by cgulliver** [comment]
Artifacts location updated

**Comment by cgulliver** [comment]
Artifacts location updated
