### ISSUE TITLE
cfn-init fails on redhost

### ISSUE THREAD

**Issue by dsshaw1500** [aws-samples/protecting-workloads-workshop#7]
I'm stuck in the BUILD stage, just importing the templates.  I've tried in multiple regions several times.  They get stuck on the RedHost, so I stopped rollback and logged onto the host that fails to send the response.

Anyone know what is wrong?  Here are the error messages in the logs:

 grep -ni 'error\|failure' $(sudo find /var/log -name cfn\* -or -name cloud-init\*)
/var/log/cloud-init.log:456:Sep 03 17:44:19 cloud-init[2890]: main.py[DEBUG]: Ran 14 modules with 0 failures
/var/log/cloud-init.log:558:Sep 03 17:44:53 cloud-init[3044]: main.py[DEBUG]: Ran 10 modules with 0 failures
/var/log/cloud-init.log:592:ProcessExecutionError: Unexpected error while running command.
/var/log/cloud-init.log:613:RuntimeError: Runparts: 1 failures in 1 attempted commands
/var/log/cloud-init.log:649:Sep 03 17:45:36 cloud-init[3573]: main.py[DEBUG]: Ran 9 modules with 1 failures
/var/log/cloud-init-output.log:402:Error: Package: python3-wheel-0.30.0a0-6.amzn2.0.1.noarch (amzn2extra-python3)

**Comment by keithrozario** [comment]
Same here -- Cloudformation fails across all regions.

**Comment by dsshaw1500** [comment]
I guess no one with the knowledge of what needs to be installed and configured on redhost is monitoring this.  

If someone know what needs to be installed on the redhost and what the configuration needs to be, that’s all I need to keep going.  It would be appreciated.  I want to use this workshop as a demo while teaching Security Engineering on AWS, and several AAIs have recommended it, but it hasn’t worked in over a month and my class is only a week away.

I would give someone a virtual hug and high-five if you could help me get the redhost configured so I can proceed with this demo!! 

Thanks for the effort and support!!!

**Comment by dsshaw1500** [comment]
@keithrozario , 

Caveat this with "I am not a Linux guru."  I grew up with Windows and know only enough Linux as necessary for AWS purposes.  I solved the RedTeamHost issue, but... I probably am doing things the wrong way, too many things, perhaps even the wrong things... none-the-less, I have the workshop doing it's thing.

What I did:
- disabled rollback if stack fails
- changed the redteamhost cinit response timeout to 30 mins (so I wouldn't have to stare at the screen and had time to remediate). 

RedTeamHost session manager console:
```
sudo su
#!/bin/bash -xe
# yum update -y
trap 'printf "\n"' DEBUG
export PS1="\n[\u@\h \W] $ "
yum update -y
yum install httpd -y  
cd /usr/bin
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
aws --version
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
sudo yum install python37
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
export PATH=/root/.local/bin:$PATH
source ~/.bash_profile
amazon-linux-extras enable python3.9
amazon-linux-extras install -y python3.9
yum install -y curl git python-pip
pip install awsebcli --upgrade --user
eb --version
pip install awsebcli --upgrade --user
pip install httpie
export PATH=/usr/local/bin:$PATH
source ~/.bash_profile
/usr/bin/aws configure set region <YOUR_REGION>
/opt/aws/bin/cfn-init -v --stack <YOUR_STACK_NAME> --resource RedTeamHost --configsets Scanner_Install --region <YOUR_REGION>
/opt/aws/bin/cfn-signal -e $? --stack <YOUR_STACK_NAME> --resource RedTeamHost --region <YOUR_REGION>
cd /usr/bin; curl -O https://s3.amazonaws.com/protecting-workloads-workshop/public/artifacts/scanner.py
echo python3 /usr/bin/scanner.py http://<DNS_OF_YOUR_ALB_CREATED_BY_THIS_STACK> > /usr/bin/runscanner; chmod 755 /usr/bin/runscanner

```
for this next section, I did it manually because I couldn't get the stupid c-init join to work.  so I....
```
nano runratest
```
<paste the following into the file>

```
#!/bin/bash
#Script to trigger WAF rate-based rule
COUNTER=0
for j in `seq 1 400`;
do
  let COUNTER++
  printf "Request %d\n response" $COUNTER
  http -h --form POST http://<DNS_OF_YOUR_ALB_CREATED_BY_THIS_STACK>/form.php x-csrf-token:89a77f7afaedc09870a99eb15ccda32fe2a8b3f2
done
```
ctrl+o , ENTER to save, ctrl+x to exit nano

```
chmod 755 runratest
runratest
runscanner
```

Well, that's what I did, and it works for me.  Good luck!

**Comment by keithrozario** [comment]
Thanks @dsshaw1500 , issue was caused by the `yum install httpie` which would fail, and hence prevent the instance from sending the signal.

I fixed this by pip3 installing httpie instead, already made a pull request, but the fixed CF template that would work without manual intervention is here: https://github.com/keithrozario/protecting-workloads-workshop

I got the inspiration from your fix, since you pip installed it as well :)
